version: '3'
volumes:
  elasticsearch:
networks:
  elastic:
    driver: bridge
services:
  elasticsearch:
    image: elasticsearch:6.5.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - elastic
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
  kibana:
    image: kibana:6.5.4
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
    links:
      - elasticsearch
    networks:
      - elastic
    depends_on:
      - elasticsearch
